### ISSUE TITLE
thoughts on a pregenerated mode?

### ISSUE THREAD

**Issue by bprodoehl** [chakrit/randstream#1]
I really like this package, but I've been wishing that there was a mode that would return data from a random start position in a pregenerated block of random data.  I can get maybe 600Mbps using the pseudo mode, but I should be able to get about 4x that if I were just doing a copy.

Do you have any opinions on that?  Would you accept a pull request if I submit one?

**Comment by chakrit** [comment]
PR -> sure : )

**Comment by chakrit** [comment]
I think we could do something like having a setTimeout infinite loop generating data and another one writing them onto the wire basically mini-pipelining the thing.

**Comment by bprodoehl** [comment]
Ok, I was trying to get away from having the data generated on the fly after a warmup.  I'll submit a pull request of what I was thinking.
